language: python
group: travist_latest

env:
  global:
    - CYTHON_TRACE_NOGIL=1
    - MPLBACKEND=agg
      # scipy and matplotlib are in MDAnalysis
    - CONDA_DEPENDENCIES="MDAnalysis MDAnalysisTests pytest pytest-cov codecov"
    - CONDA_CHANNELS='conda-forge'
    - CONDA_CHANNEL_PRIORITY=True


# Run jobs on container-based infrastructure, can be overridden per job
matrix:
  include:
    # Extra includes for OSX since python language is not available by default on OSX
    - os: osx
      language: generic
      env: PYTHON_VERSION=3.6
    - os: osx
      language: generic
      env: PYTHON_VERSION=3.7


    - os: linux
      dist: bionic
      language: generic  # No need to set Python version since its conda
      env: PYTHON_VERSION=3.6
    - os: linux
      dist: bionic
      language: generic
      env: PYTHON_VERSION=3.7
    - os: linux
      dist: bionic
      language: generic
      env: PYTHON_VERSION=3.8


before_install:
    # Additional info about the build
  - uname -a
  - df -h
  - ulimit -a
  - |
     if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
       wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh
     else
       wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
     fi
  - mkdir $HOME/.conda
  - bash miniconda.sh -b -p $HOME/miniconda
  - $HOME/miniconda/bin/conda init bash
  - source ~/.bash_profile
  - conda activate base
  - conda update --yes conda


install:
  - conda env create python=$PYTHON_VERSION -f devtools/conda-envs/test_env.yml
  - conda activate test 
  - python -V
    # Build and install package
  - python setup.py develop --no-deps


script:
  - pytest -v --cov=MDRestraintsGenerator MDRestraintsGenerator/tests/

notifications:
    email: false

after_success:
  - codecov
